config/routes.rb
Giffindor::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :gif_posts
  resources :favorites, only: [:show, :create, :destroy]
  get "home/index"
  root 'gif_posts#index'
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :gif_post
  validates :gif_post, presence: true, :uniqueness => {scope: :user_id}
end

app/models/gif_post.rb
class GifPost < ActiveRecord::Base
  belongs_to :user
  has_many :favorites
  validates :body, presence: true
  validates :url, presence: true, uniqueness: { scope: :user_id, message: "You have already posted this image. Please pick a different image and try again." }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
  # Setup accessible (or protected) attributes for your model
  validates_presence_of :username
  has_many :gif_posts
  has_many :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:sign_in) << :username
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  respond_to :json

  # GET /favorite
  def show
    set_favorite
    respond_with @favorite, location: nil
  end

  # POST /favorites
  def create
    @favorite = current_user.favorites.create(favorite_params)
    respond_with @favorite, location: nil
  end

  # DELETE /favorites/1
  def destroy
    @favorite = current_user.favorites.find(params[:id])
    @favorite.destroy
    respond_to do |format|
      format.json {render json: {}, status: :ok, location: nil}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def favorite_params
      params.delete(:user_id)
      params.require(:favorite).permit(:gif_post_id)
    end
end

app/controllers/gif_posts_controller.rb
class GifPostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_gif_post, only: [:show]
  before_action :set_current_user_gif_post, only: [:edit, :update, :destroy]
  respond_to :json, :html
  # GET /gif_posts
  def index
    @gif_posts = GifPost.order("created_at DESC")
    respond_with @gif_posts
  end

  # GET /gif_posts/1
  def show
    respond_with @gif_post
  end

  # GET /gif_posts/new
  def new
    @gif_post = current_user.gif_posts.new
  end

  # GET /gif_posts/1/edit
  def edit
  end

  # POST /gif_posts
  def create
    @gif_post = current_user.gif_posts.create(gif_post_params)
    respond_with @gif_post
  end

  # PATCH/PUT /gif_posts/1
  def update
    if @gif_post.update(gif_post_params)
      respond_with @gif_post
    end
  end

  # DELETE /gif_posts/1
  def destroy
    @gif_post.destroy
    respond_to do |format|
      format.html {redirect_to gif_posts_url}
      format.json {render json: {}, status: :ok}
    end
  end

  def details
    respond_to do |format|
      format.html { render "ember/index" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gif_post
      @gif_post = GifPost.find(params[:id])
    end

    def set_current_user_gif_post
      @gif_post = current_user.gif_posts.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def gif_post_params
      params.require(:gif_post).permit(:url, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/gif_posts/_form.html.erb
<%= form_for(@gif_post) do |f| %>
  <% if @gif_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gif_post.errors.count, "error") %> prohibited this gif_post from being saved:</h2>

      <ul>
      <% @gif_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gif_posts/edit.html.erb
<h1>Editing gif_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @gif_post %> |
<%= link_to 'Back', gif_posts_path %>

app/views/gif_posts/index.html.erb
<% if current_user %>
  <div id="new-post-container">
    <h1 class="no-top-margin">Recently Shared Gifs</h1>
  </div>
<% else %>
  <div class="row headline">
    <div class="col-md-8 col-sm-8 col-md-offset-2">
      <h1>Recently Shared Gifs</h1>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-8 col-sm-8 col-md-offset-2">
    <section id="gif-posts-container" class="gif-list">
      Loading...
    </section>
  </div>
</div>

app/views/gif_posts/new.html.erb
<h1>New gif_post</h1>

<%= render 'form' %>

<%= link_to 'Back', gif_posts_path %>

app/views/gif_posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <section class="gif-list">
      <article class="gif-entry" data-gif-entry data-gif-post-id="<%= @gif_post.id %>">
        <div class="gif-entry-image"><%= image_tag(@gif_post.url, class: "framed") %></div>
        <p class="gif-entry-body"><%= @gif_post.body %></p>
        <div class="gif-entry-delete">
          <a href="<%= gif_post_path(@gif_post) %>" data-gif-delete data-gif-post-id="<%= @gif_post.id %>" class="btn btn-danger" rel="nofollow">Delete</a>
        </div>
        <p class="gif-entry-user">Shared by <%= @gif_post.user.username %></p>
        <p class="gif-entry-permalink"><%= link_to 'Permalink', @gif_post %></p>
        <div style="clear:both;"></div>
      </article>
    </section>
  </div>
</div>

<%= link_to 'Back', gif_posts_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Giffindor</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="current-user-id" content="<%= current_user.id if current_user%>" />
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top gryffindor-striped" role="navigation">
      <div class="container">
        <a class="navbar-brand navbar-logo" href="<%= root_url %>"></a>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <p class="navbar-text">Signed in as <%= current_user.username %></p>
            <li><%= link_to 'My profile', edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <p class="navbar-text">Not signed in</p>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>